<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita3035484ec8dadef27c4a16f0900ac2e
{
    public static $prefixLengthsPsr4 = array (
        'Y' => 
        array (
            'Yabacon\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Yabacon\\' => 
        array (
            0 => __DIR__ . '/..' . '/yabacon/paystack-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita3035484ec8dadef27c4a16f0900ac2e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita3035484ec8dadef27c4a16f0900ac2e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
